<script setup>
import { computed } from 'vue'
import { RouterLink } from 'vue-router'
import { ArrowRight, Heart, ShieldCheck, UsersRound, BookOpenCheck, Leaf } from '@lucide/vue'
import SectionHeading from '../components/SectionHeading.vue'
import ProgramCard from '../components/ProgramCard.vue'
import ImpactNumber from '../components/ImpactNumber.vue'
import { gallery, pageContent, photos, programs } from '../data/site'

const props = defineProps({ pageKey: { type: String, required: true } })
const page = computed(() => pageContent[props.pageKey])
const icons = [ShieldCheck, Heart, Leaf, UsersRound]
</script>

<template>
  <div>
    <section class="page-hero"><img :src="page.image" :alt="page.title" loading="eager" fetchpriority="high" decoding="async" /><div class="container page-hero-content"><span class="eyebrow">{{ page.eyebrow }}</span><h1 class="display">{{ page.title }}</h1><p>{{ page.intro }}</p><div class="breadcrumb"><RouterLink to="/">Home</RouterLink><span>/</span><span>{{ page.title }}</span></div></div></section>
    <section class="section" v-reveal><div class="container about-grid"><div class="about-copy"><span class="eyebrow">{{ page.eyebrow }}</span><h2 class="display">{{ page.sectionTitle }}</h2><p>{{ page.body }}</p><p>{{ page.extra }}</p><RouterLink class="button button-primary" to="/contact">Connect with us <ArrowRight :size="15" /></RouterLink></div><div class="about-collage"><div class="collage-main"><img class="photo" :src="page.image" :alt="page.title + ' in Liberia'" loading="lazy" decoding="async" /></div><div class="collage-small"><img class="photo" :src="photos.aboutSmall" alt="Girls working together" loading="lazy" decoding="async" /></div><div class="collage-note">Every girl.<br />Every voice.</div></div></div></section>
    <section v-if="pageKey === 'about'" id="mission" class="section focus-section" v-reveal><div class="container"><SectionHeading eyebrow="Our purpose" title="A Liberia where every girl can thrive." description="Our mission is to empower adolescent girls and young women through advocacy, leadership development, education, and community engagement. Our vision is a Liberia where every girl is empowered, heard, protected, and equipped to reach her full potential." /><div class="focus-grid"><article class="focus-card"><span class="focus-icon"><Heart :size="21" /></span><h3>Our mission</h3><p>Empowering adolescent girls and young women through advocacy, leadership development, education, and community engagement.</p></article><article class="focus-card"><span class="focus-icon"><BookOpenCheck :size="21" /></span><h3>Our vision</h3><p>A Liberia where every girl is empowered, heard, protected, and equipped to reach her full potential.</p></article><article class="focus-card"><span class="focus-icon"><ShieldCheck :size="21" /></span><h3>Our values</h3><p>We lead with dignity, inclusion, accountability, and care for the people and communities we serve.</p></article><article class="focus-card"><span class="focus-icon"><UsersRound :size="21" /></span><h3>Our approach</h3><p>We listen first, work alongside local partners, and put girls’ leadership at the center of change.</p></article></div></div></section>
    <section v-if="pageKey === 'programs'" class="section" v-reveal><div class="container"><SectionHeading eyebrow="Ways to take part" title="Explore our programs" description="Each program creates practical opportunities for girls to learn, connect, and take the lead." /><div class="program-grid"><ProgramCard v-for="program in programs" :key="program.slug" :program="program" /></div></div></section>
    <section v-if="pageKey === 'impact'" class="impact-strip" v-reveal><div class="container impact-grid"><div class="impact-item"><span class="impact-icon"><UsersRound :size="19" /></span><div><ImpactNumber :value="5000" suffix="+" /><span>girls reached</span></div></div><div class="impact-item"><span class="impact-icon"><BookOpenCheck :size="19" /></span><div><ImpactNumber :value="150" suffix="+" /><span>peer educators trained</span></div></div><div class="impact-item"><span class="impact-icon"><Leaf :size="19" /></span><div><ImpactNumber :value="20" suffix="+" /><span>communities engaged</span></div></div><div class="impact-item"><span class="impact-icon"><Heart :size="19" /></span><div><ImpactNumber :value="15" suffix="+" /><span>projects delivered</span></div></div></div></section>
    <section v-if="pageKey === 'news' || pageKey === 'events'" class="section" v-reveal><div class="container"><SectionHeading :eyebrow="page.eyebrow" :title="pageKey === 'news' ? 'Stories from the field' : 'Gather with us'" description="Discover the people and ideas moving our work forward." /><div class="interior-grid"><article v-for="(item, index) in gallery.slice(0, 3)" :key="item.label" class="interior-card"><img :src="item.image" :alt="item.label" loading="lazy" decoding="async" /><div class="interior-card-copy"><span class="eyebrow">{{ pageKey === 'news' ? 'Field notes' : 'Community event' }}</span><h3>{{ pageKey === 'news' ? ['Girls building confidence through peer learning', 'Community voices shape local action', 'Young leaders imagine a greener future'][index] : ['Girls’ leadership workshop', 'Community dialogue day', 'Peer educator gathering'][index] }}</h3><p>{{ pageKey === 'news' ? 'Young leaders are creating new opportunities to learn, speak up, and support one another.' : 'Join girls, families, and local partners for a day of shared learning and connection.' }}</p><RouterLink class="text-link" :to="pageKey === 'news' ? '/contact' : '/volunteer'">{{ pageKey === 'news' ? 'Read the story' : 'Get involved' }} <ArrowRight :size="14" /></RouterLink></div></article></div></div></section>
  </div>
</template>